### ISSUE TITLE
Every ipsw download prints an advertisement for tihmstar's ios 8 jailbreak

### ISSUE THREAD

**Issue by KritantaDev** [blacktop/ipsw#20]
title.

**Comment by blacktop** [comment]
thank you for letting me know, i used to query https://canijailbreak.com/ to let you know if what you were downloading was jailbreakable, but it looks like he stopped updating the site 😞

**Comment by KritantaDev** [comment]
if you ever feel like some web-scraping therapy, https://www.theiphonewiki.com/wiki/Jailbreak/13.x the iPhone wiki has tables for every jailbreak released for every version of iOS thus far; something could probably be (poorly) rigged up to parse that

**Comment by blacktop** [comment]
I believe I have removed that now?

**Comment by KritantaDev** [comment]
yep, brew wasn't showing an update for the longest time and I only got the latest version today, looks to be good.

**Comment by blacktop** [comment]
I've had others tell me that about brew too, which is strange because mine upates immediately, but I also have 

`alias brewu="brew update;brew upgrade;brew cleanup;brew doctor;brew cu -a"` that I have OCD about and run at least 10 times a day ;)

I also just added a :new: cmd to update `ipsw` - https://blacktop.github.io/ipsw/docs/commands/update/
