### ISSUE TITLE
macos beta images download

### ISSUE THREAD

**Issue by doronz88** [blacktop/ipsw#25]
Hi again :)

Is it possible to download macos beta images also? I tried both `ipsw download beta <build>` and `ipsw download macos --build <build>` but with no success.

**Comment by blacktop** [comment]
I believe what is supported is release IPSW for M1 macs (sadly apple doesn't publish beta IPSWs for macOS (yet). However you can download beta OTAs for M1 macOS. 

I did add the ability to download macOS installers, but didn't have an extra system to try the output installer on (though I guess could have tried a VM or another partition. You can see what installers are currently able to downloaded with `ipsw download macos --installer`

I haven't "wired it up yet" because I haven't tested it, but it does create the installers, however due to some sandboxing in macOS you have to avoid running it from certain directories. 

I can hook it up today if you want to try and let me know 😉

**Comment by doronz88** [comment]
I didn't dive deep into the code, but this project seems looks like it can accomplish the task probably by scraping a different source.

https://github.com/ninxsoft/Mist

It'll be cool to have the option on `ipsw` also

**Comment by blacktop** [comment]
Yeah, that functionality does exist in a ipsw currently it's just not exposed. I'll try to expose it tonight. Just to confirm though, you want beta "installers" and NOT beta macOS IPSWs correct?

**Comment by doronz88** [comment]
Didn't look too deep into that. I cannot extract the `.ipsw` from the installer? if it just downloads from the internet it's not great, but still fine.

**Comment by blacktop** [comment]
@doronz88 would you be willing to enter you dev account user/password?  I'm currently working in the `feature/dev-portal` branch and am really close to having a working solution (which would allow as fast as they are posted) beta downloads of ALL platforms, including Xcode, KDKs etc etc 

but just wanted to know if anyone other than me would use it?

**Comment by doronz88** [comment]
That would be amazing 😍

**Comment by blacktop** [comment]
Later on I'll make it "cron-able" but here it is - https://github.com/blacktop/ipsw/pull/30 🎉

**Comment by doronz88** [comment]
That would also be great 😃
