### ISSUE TITLE
Nitpick: Command help can be out of sync with the actual commands & online docs

### ISSUE THREAD

**Issue by glen-mac** [blacktop/ipsw#76]
Just a really small thing. The command help can be out of sync. Take for example the command:
```
$ ipsw download beta

Error: requires at least 1 arg(s), only received 0
   ⨯ requires at least 1 arg(s), only received 0
```

This is a command that exists, but when we try and get this command listed from the parent "download" command:
```
$ ipsw download

Download Apple Firmware files (and more)

Usage:
  ipsw download [flags]
  ipsw download [command]

Available Commands:
  dev         Download IPSWs (and more) from https://developer.apple.com/download
  git         Download github.com/orgs/apple-oss-distributions tarballs
  ipsw        Download and parse IPSW(s) from the internets
  macos       Download macOS installers
  oss         Download opensource.apple.com file list for macOS version
  ota         Download OTAs
  rss         Read Releases - Apple Developer RSS Feed
  tss         🚧 Download SHSH Blobs

Flags:
      --black-list stringArray   iOS device black list
  -b, --build string             iOS BuildID (i.e. 16F203)
  -y, --confirm                  do not prompt user for confirmation
  -d, --device string            iOS Device (i.e. iPhone11,2)
  -h, --help                     help for download
      --insecure                 do not verify ssl certs
  -m, --model string             iOS Model (i.e. D321AP)
      --proxy string             HTTP/HTTPS proxy
  -_, --remove-commas            replace commas in IPSW filename with underscores
      --restart-all              always restart resumable IPSWs
      --resume-all               always resume resumable IPSWs
      --skip-all                 always skip resumable IPSWs
  -v, --version string           iOS Version (i.e. 12.3.1)
      --white-list stringArray   iOS device white list

Global Flags:
      --config string   config file (default is $HOME/.ipsw.yaml)
  -V, --verbose         verbose output

Use "ipsw download [command] --help" for more information about a command.
```

the "beta" subcommand isn't listed

**Comment by glen-mac** [comment]
the beta command is definitely of use to me and some others, and same would go for an ota variant (see other issue).

if you ever change your mind on this however, maybe an `--input` file for a file containing newline separated list of ipsws might be a replacement?

**Comment by blacktop** [comment]
Ok I'll reevaluate making this cmd a first class citizen once again and try and modernize it to match the other download commands

**Comment by blacktop** [comment]
Hey so I took another look at the iphonewiki and it is VERY complex and I'm not really sure how to proceed.  

For starters crawling their tables is a nightmare because there is 0 standardization and I EVEN am using the API now and not just scraping and it is still VERY gross to work with.  

Also OTAs don't really lend themselves to being "categorized" let me show you what I mean - https://www.theiphonewiki.com/wiki/OTA_Updates/iPhone/15.0

How would you query those OTA zips?  `ipsw download wiki --version 15.0 --prereqver 14.0.1 --ota --device iPhone8,1 --board N71AP` ???

I guess typically peeps would want the n/a n/a version of OTAs?  

So it's parsing HTML tables with random spans everywhere OR parsing wikitable markup with random spans everywhere.

# 🤮

**Comment by blacktop** [comment]
It looks like the ipsw.me dude has old OTAs, maybe I could add support for those?

**Comment by blacktop** [comment]
So I have a 🆕 hidden 🤫 cmd called `ipsw download wiki` for you to try.  It isn't a complete solution, but it pulls ALL the IPSWs now including Apple Watch #63 for the very few that the wiki hosts.

```bash
❯ ipsw download wiki --device Watch6,9 -V
   • URLs to download:
      • https://updates.cdn-apple.com/2021FallFCS/fullrestores/071-99434/9B52ADA2-3E27-4E68-93EF-D3555E3D5B26/Watch6,9_8.0_19R346_Restore.ipsw
      • https://updates.cdn-apple.com/2021FCSFall/fullrestores/002-12850/16820EE6-A501-4583-A7D9-F151F93530BE/Watch6,9_8.0.1_19R354_Restore.ipsw
      • https://updates.cdn-apple.com/2021FCSFall/fullrestores/071-65932/1F21232C-1FCA-4573-A94E-F2E3DFF470DF/Watch6,9_8.1_19R570_Restore.ipsw
      • https://updates.cdn-apple.com/2022SpringFCS/fullrestores/002-61353/96577C33-63D0-4CA9-9F20-2DB9594DB392/Watch6,9_8.4.1_19S550_Restore.ipsw
? You are about to download 4 ipsw files. Continue? (y/N)
```

**Comment by glen-mac** [comment]
ah lovely! thank you!

**Comment by glen-mac** [comment]
would it be possible to be able to filter for release/beta and to specify --dyld and --kernelcache ?

**Comment by blacktop** [comment]
Adding support for `--kernel` and `--pattern` now
```bash
❯ ipsw download wiki --device Watch6,9 --kernel
? You are about to download 4 ipsw files. Continue? Yes
   • Parsing remote IPSW       build=19R346 devices=Watch6,9 version=8.0
   • Extracting remote kernelcache
      • Writing 19R346__Watch6,9/kernelcache.release.Watch6,9
```
*NOTE:* `--dyld` support for IPSWs is coming, but not currently possible *remotely*

**Comment by blacktop** [comment]
I see about adding support for dividing release and beta, but can you explain how you envision using that cmd?  Because I'm currently just using the URLs to determine what they are so all the beta URLs for say iOS 15.4 with just say `version=15.4` BUT the build will change, so for `ipsw download wiki` cmds I kinda need the users to supply `--build` to get precisely what they need until I can finish writing a parser for mediawiki markup syntax

**Comment by blacktop** [comment]
revamped the `ipsw download wiki`  cmd  in latest release pushing out now (also it now parses the MediaWiki Markdown format exposed by the API
